# -*- coding: utf-8 -*-
"""breast cancer.24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/161yWBhH4tO_QBR249w95R8g1ItsSolXW
"""

from google.colab import drive
drive.mount('/content/drive')

"""impoerting google drive"""

import pandas as pd
data=pd.read_csv("//content/breast cancer.csv")

data

"""# New Section"""

data.shape

data.info

data.head()

data.tail()

data.describe()

data["area_worst"].value_counts()

data.duplicated()

data.isnull().sum()

from sklearn.preprocessing import LabelEncoder
target='diagnosis'
label_encoder=LabelEncoder()
data[target]=label_encoder.fit_transform(data[target])

import matplotlib.pyplot as plt
plt.plot(data["radius_mean"])
plt.xlabel("radius_mean")
plt.ylabel("texrure_mean")
plt.title("line plot")
plt.show()

import plotly.express as px
px.histogram(data_frame=data,x='radius_mean',color='diagnosis',color_discrete_sequence=['#A865C9','#f6abb6'])

import pandas as pd

# Assuming 'df' is your DataFrame
feature_names = data.columns.tolist()

feature_names